SELECT * FROM departments;

SELECT FIRST_NAME, EMAIL, HIRE_DATE FROM employees;

SELECT FIRST_NAME, EMAIL, salary, salary*12 FROM employees;

SELECT FIRST_NAME, EMAIL, salary "Salário", salary*12 "Salário Anual" FROM employees;

SELECT FIRST_NAME, EMAIL,
'Sálario:' || salary "Salário",
salary*12 "Salário Anual" 
FROM employees;

SELECT DISTINCT job_id FROM employees ORDER BY job_id;

SELECT FIRST_NAME, LAST_NAME, SALARY FROM employees WHERE salary BETWEEN 10000 AND 20000;
SELECT FIRST_NAME, LAST_NAME, SALARY FROM employees WHERE salary NOT BETWEEN 10000 AND 20000;

SELECT FIRST_NAME, LAST_NAME, SALARY, MANAGER_ID FROM employees WHERE manager_id IN (101,145,149);
SELECT FIRST_NAME, LAST_NAME, SALARY, MANAGER_ID FROM employees WHERE manager_id NOT IN (101,145,149);

SELECT FIRST_NAME, LAST_NAME, SALARY FROM employees WHERE FIRST_NAME LIKE 'S%';
SELECT FIRST_NAME, LAST_NAME, SALARY FROM employees WHERE FIRST_NAME NOT LIKE 'S%';

SELECT FIRST_NAME, LAST_NAME, SALARY FROM employees WHERE MANAGER_ID IS NULL;
SELECT FIRST_NAME, LAST_NAME, SALARY FROM employees WHERE MANAGER_ID IS NOT NULL;

SELECT FIRST_NAME, LAST_NAME, SALARY, JOB_ID FROM employees WHERE SALARY BETWEEN 2000 AND 3000 AND JOB_ID = 'ST_CLERK';

SELECT FIRST_NAME, LAST_NAME, SALARY, JOB_ID FROM employees WHERE SALARY BETWEEN 2000 AND 3000 OR JOB_ID = 'ST_CLERK';

SELECT FIRST_NAME, LAST_NAME, SALARY, JOB_ID FROM employees WHERE SALARY > 8000 AND JOB_ID = 'ST_CLERK' OR JOB_ID = 'ST_MAN';
SELECT FIRST_NAME, LAST_NAME, SALARY, JOB_ID FROM employees WHERE SALARY > 8000 AND (JOB_ID = 'ST_CLERK' OR JOB_ID = 'ST_MAN');

SELECT FIRST_NAME, LAST_NAME, SALARY FROM employees WHERE SALARY BETWEEN 10000 AND 20000 ORDER BY LAST_NAME;
SELECT FIRST_NAME, LAST_NAME, SALARY FROM employees WHERE SALARY BETWEEN 10000 AND 20000 ORDER BY LAST_NAME DESC;

SELECT FIRST_NAME, LAST_NAME, SALARY FROM employees WHERE SALARY BETWEEN 10000 AND 20000 ORDER BY SALARY DESC, LAST_NAME;

