SELECT AVG(SALARY) FROM EMPLOYEES;

SELECT MIN(SALARY), MAX(SALARY), SUM(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID = 30;

SELECT COUNT(*) FROM EMPLOYEES WHERE DEPARTMENT_ID = 30;

SELECT DEPARTMENT_ID, AVG(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID, AVG(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID ORDER BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID DEPT_ID, JOB_ID, SUM(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID, JOB_ID;

SELECT DEPARTMENT_ID, AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID NOT IN (10,20,30) GROUP BY DEPARTMENT_ID ORDER BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID, JOB_ID, AVG(SALARY), SUM(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID, JOB_ID ORDER BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID, MAX(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID HAVING MAX(SALARY) > 10000;

SELECT DEPARTMENT_ID, AVG(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID HAVING AVG(SALARY) > 6000 ORDER BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID, COUNT(*) FROM EMPLOYEES GROUP BY DEPARTMENT_ID HAVING MAX(SALARY) > 10000 ORDER BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID, COUNT(*) FROM EMPLOYEES WHERE DEPARTMENT_ID IN (10,20,30,40) GROUP BY DEPARTMENT_ID HAVING MAX(SALARY) > 10000 ORDER BY DEPARTMENT_ID;

